### ISSUE TITLE
Outdated CCA dependency

### ISSUE THREAD

**Issue by UpcraftLP** [CottonMC/UniversalComponents#1]
You are using an outdated identifier for CCA and still pulling it from the nerdhub org (`com.github.NerdHubMC.Cardinal-Components-API`). Now anyone who also depends on the _new_ CCA (`com.github.OnyxStudios.Cardinal-Components-API`) will get a duplicate dependency modid when launching in a dev workspace.

Also, while you're at it maybe update CCA to `2.3.4` (1.15.2)

**Comment by LemmaEOF** [comment]
Huh, could have sworn I'd done this. Oh well.
