### ISSUE TITLE
Crash when inserting to Stockpile barrels via InvBEWrapper

### ISSUE THREAD

**Issue by branchpanic** [CottonMC/UniversalComponents#11]
**Describe the bug**

When UniversalComponents is present, attempting to insert unmatching items into Stockpile barrels crashes the game because Stockpile's `Inventory.isValid` implementation is not called.

Here are some logs I've gotten from user reports at https://github.com/branchpanic/stockpile/issues/100.

https://pastebin.com/a0FCmA7V
https://pastebin.com/CPksU9Di

Here is my reproduction using only Stockpile, UC, and the dependencies listed below.

https://gist.github.com/branchpanic/7fe234e6997caa3eaae8c376929ac5d1

**To Reproduce**

1. Place a Stockpile barrel and add any item.
2. Place a hopper facing the barrel.
3. Add any differing item to the hopper. The game will crash with the above stack trace upon the hopper trying to insert.

Repeat the above steps without UniversalComponents to observe the expected behavior (no crash).

**Version of the (please complete the following information):**
 - Universal Components 0.7.2+1.16-pre2
 - Cardinal Components API 2.4.2
 - Stockpile 1.1.4+1.16.1
 - Fabric API 0.16.0+build.384-1.6.1
 - Minecraft 1.16.1

**Additional context** *Optional*

[InvBEWrapper](https://github.com/CottonMC/UniversalComponents/blob/0166a8071fb00b65b498cf7a4faf6fcbfc24df35/src/main/java/io/github/cottonmc/component/compat/vanilla/InvBEWrapper.java) uses the default implementation of `Inventory.isValid(int, ItemStack)`, which always returns true. Stockpile barrels override this to accept only the contained item. Perhaps delegating this method, too, to `inv` would resolve the issue?

Thanks!

**Comment by LemmaEOF** [comment]
oh right, `Inventory#isValid` exists. That should be a quick fix when I've got the time.
