### ISSUE TITLE
onyxstudios in cardinal components url in build.gradle should be lowercase

### ISSUE THREAD

**Issue by 1holz** [CottonMC/UniversalComponents#13]
onyxstudios in cardinal components url in build.gradle should be lowercase. So "io.github.OnyxStudios.Cardinal-Components-API:cardinal-components-base:${project.cardinal_version}" should become "io.github.onyxstudios.Cardinal-Components-API:cardinal-components-base:${project.cardinal_version}" else it throws an exception saying that it didn't found it (at least for me)

**Comment by UpcraftLP** [comment]
closed by #14
