### ISSUE TITLE
Prevent Item Inventory nesting

### ISSUE THREAD

**Issue by biom4st3r** [CottonMC/UniversalComponents#2]
**Is your feature request related to a problem? Please describe.**
Repeatedly nesting Item Inventories can "book ban" a player and requiring an inventory wipe

**Describe the solution you'd like**
a way to optionally(at the mod makers discretion) and by default restrict placing Item inventories in other Item inventories

**Comment by LemmaEOF** [comment]
oh yeah, that'd be a good idea. I'll add that in soon. We just ran into an issue like this on the Modfest server.

**Comment by Frontrider** [comment]
I'd say disable it by default on the component, then allow the mod to re-enable it when applicable. You can put shulkers into chests once.

**Comment by LemmaEOF** [comment]
This is done in dev but haven't put a new version on maven just yet
