### ISSUE TITLE
Container#onSlotClick being called 2 times causes problems

### ISSUE THREAD

**Issue by 1holz** [CottonMC/UniversalComponents#3]
**Describe the bug**
ClientPlayerInteractionManager calles onSlotClick (in the Container Class) two times (on the client and the server) since an inventory component is the same on both sides this edits the inventory component two times

**Expected behavior**
the inventory component should only be edited once

**Version:**
 - UniversalComponents: 0.5.6+1.15.2
 - CardinalComponents: 2.3.4
 - Fabric API: 0.7.1+build.301-1.15
 - Minecraft: 1.15.2

**Comment by Juuxel** [comment]
You should not share the same `Inventory` instance on the logical server and the logical client.

**Comment by 1holz** [comment]
but isn't the inventory component shared by universal components?

**Comment by Juuxel** [comment]
You're the one controlling what gets passed to the screen controller. On the client, it should get an inventory that is only used on the client. When `onSlotClick` is called it updates both the client-side and the server-side `Inventory` instances, but both only once so there's no duplication.

**Comment by 1holz** [comment]
but doesn't that mean I can't use a component for an inventory? or should I make one component for each side?

**Comment by Juuxel** [comment]
@Boundarybreaker would know more about that. In general, you should *not* share any mutable objects between the sides: even singleplayer has both a `ClientPlayerEntity` and a `ServerPlayerEntity`.

**Comment by Juuxel** [comment]
Eh, maybe Boundary needs to take a look at this, actually. I'm not that familiar with using CCA for inventories, but in general you definitely can just pass a dummy `BasicInventory` to a `Container` constructor.

**Comment by LemmaEOF** [comment]
I might know the issue here, but I'll have to check something really quick.

**Comment by LemmaEOF** [comment]
I can't really see why this would be happening, sadly :( I don't really understand the onSlotClick code, but it doesn't look like there should be any way it should desync unless something is going *really* wrong. Do you have a listener to call `BlockEntityClientSerializable#sync()` on your inventory component?

**Comment by Juuxel** [comment]
`Container` should synchronise items automatically.

**Comment by LemmaEOF** [comment]
hmm, that probably assumes a real vanilla inventory though. I'm really not sure what to do; I haven't encountered this issue in my own projects using UC.

**Comment by 1holz** [comment]
this was propably just me doing things wrong sorry
