### ISSUE TITLE
Unit.format returning always the same amount of decimals 

### ISSUE THREAD

**Issue by 1holz** [CottonMC/UniversalComponents#4]
So I have the return value of Unit.format diplayed on the tooltip in a gui.  If the last decimal is 0 it won't be diplayed. If the value now quickly changes this lets text after this value shift fore and back making it hard to read. There should be a 0 diplayed as the last decimal not nothing.

**Comment by LemmaEOF** [comment]
I'll take a look into it. I'd thought that tooltips always left-or right-aligned.

**Comment by 1holz** [comment]
[1.zip](https://github.com/CottonMC/UniversalComponents/files/4655138/1.zip)

**Comment by LemmaEOF** [comment]
ahh, it's in the middle of a text field. I think what would be best for me to do here is to add a `format` method that defines a number of decimal places. I'll work on that when I've got time.

**Comment by UpcraftLP** [comment]
closed by #14
